name: Build & Test Zodiac Guard

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Cache Hardhat & Node Modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
            .yarn/install-state.gz
            cache
            artifacts
          key: ${{ runner.os }}-node${{ matrix.node }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Compile Contracts
        run: yarn prepare

      - name: Run Tests
        run: yarn test

      - name: Run Coverage
        run: yarn coverage

      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info

